### ISSUE TITLE
subscriptions for youtube-dl

### ISSUE THREAD

**Issue by Shigeto1** [Kthulu120/liquid_dl#11]
![chrome_2017-09-12_10-39-452_proc](https://user-images.githubusercontent.com/17693622/30334692-58d83b32-97ae-11e7-886a-b38d51164365.jpg)

adding something like pic related would be awesome

**Comment by Kthulu120** [comment]
Here's what I came up with
![capture](https://user-images.githubusercontent.com/15041351/30416569-457c4b6a-98f2-11e7-98d8-c70801dfda7a.PNG)

**Comment by Shigeto1** [comment]
looks good! hard to tell from your pic but just a few features to include off the top of my head:

- ability to choose formats on a per-channel basis (audio only for some for example)
- ability to change the youtube-dl filename output template per channel (for archiving by date)
- clickable options for setting youtube-dl options like --embed-thumbnail --embed-subs etc
- configurable exec options for using with something like rclone for automatically mirroring downloaded files to google drive etc

https://github.com/rg3/youtube-dl/blob/master/README.md#post-processing-options

**Comment by Kthulu120** [comment]
Your gonna really like the next version release, it's going to have subscriptions, subscription multi-provider support, settings, and file browser for easier access.

**Comment by greglaprise** [comment]
Do you have an estimate when the release will be?

Cheers,
Greg

**Comment by Kthulu120** [comment]
Either Tonight by 11:30pm CST or Tomorrow(September 26th) at 3:00pm CST just check back tonight if you or keep notifications on for this issue because that release will fix this issue.

**Comment by Kthulu120** [comment]
v1.2.0-alpha solves this which is from commit 6dd3de89638bb709e8fd71ce753c6f28c3f5544f @greglaprise @Shigeto1
