### ISSUE TITLE
Update Youtube-dl inside of WebUI

### ISSUE THREAD

**Issue by greglaprise** [Kthulu120/liquid_dl#12]
Feature request,

Is there a way you could add a button that updates youtube-dl?? The command to update is:

Youtube-dl -U

Thanks for the project! It's super useful!

**Comment by Kthulu120** [comment]
Added will be in the next latest release

**Comment by Kthulu120** [comment]
Resolved on commit 3f245a1392ad041e03be2a8405bf1ddedd6b6ff8
