### ISSUE TITLE
Feature request: set a default output directory

### ISSUE THREAD

**Issue by Robiinn** [Kthulu120/liquid_dl#17]
It would be great to have a setting to make a default output directory. This could be either a generic setting for all modules or a setting per module. Or perhaps it could save your last used output directory.

**Comment by Kthulu120** [comment]
Gotcha will try and add with the next release

**Comment by Robiinn** [comment]
Awesome, thanks :) I tried to add it myself but the React code is way out of my comfort zone

**Comment by Kthulu120** [comment]
No problem, the next update will drop Sunday Morning 
edit: "Next Sunday Morning" as in November 5th

**Comment by Kthulu120** [comment]
Was implemented in latest commit
